import { useNotifications } from '../hooks/useNotifications';
import { Card } from '../components/ui/card';
import { Alert, AlertDescription, AlertTitle } from '../components/ui/alert';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '../components/ui/table';

export function NotificationsPage() {
  const { notifications, loading, error } = useNotifications();

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tight">Notifications</h1>
        <p className="text-muted-foreground">
          View notifications generated by the notification-service.
        </p>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertTitle>Unable to load notifications</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {loading && !error && (
        <Card className="border-0 bg-accent/10 p-6 text-sm text-muted-foreground">
          Fetching notifications...
        </Card>
      )}

      {!loading && !error && notifications.length === 0 && (
        <Card className="border border-dashed border-border/60 bg-background p-8 text-center">
          <h3 className="mt-4 text-lg font-semibold">No notifications found</h3>
          <p className="mt-2 text-sm text-muted-foreground">
            When notifications are created, they will appear here.
          </p>
        </Card>
      )}

      {!loading && !error && notifications.length > 0 && (
        <section className="space-y-4">
          <header className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h2 className="text-2xl font-semibold tracking-tight">Notification list</h2>
              <p className="text-sm text-muted-foreground">
                {notifications.length} notification{notifications.length === 1 ? '' : 's'}
              </p>
            </div>
          </header>

          <div className="overflow-hidden rounded-lg border border-border/60">
            <Table>
              <TableHeader>
                <TableRow className="bg-muted/60">
                  <TableHead className="uppercase tracking-wide text-muted-foreground">ID</TableHead>
                  <TableHead className="uppercase tracking-wide text-muted-foreground">User ID</TableHead>
                  <TableHead className="uppercase tracking-wide text-muted-foreground">Title</TableHead>
                  <TableHead className="uppercase tracking-wide text-muted-foreground">Description</TableHead>
                  <TableHead className="uppercase tracking-wide text-muted-foreground">Timestamp</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {notifications.map((notification) => (
                  <TableRow key={notification.id} className="hover:bg-muted/40">
                    <TableCell>{notification.id}</TableCell>
                    <TableCell>{notification.userId}</TableCell>
                    <TableCell>{notification.title}</TableCell>
                    <TableCell>{notification.description}</TableCell>
                    <TableCell>{new Date(notification.timestamp).toLocaleString()}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </section>
      )}
    </div>
  );
}

